### ISSUE TITLE
call PostLogStoreLogsAsync parameter LogGroupInfo property Source No default value

### ISSUE THREAD

**Issue by yung-chu** [aliyun/aliyun-log-dotnetcore-sdk#14]
调用方法 PostLogStoreLogsAsync 传递 参数LogGroupInfo 属性 Source 不能为空 ,与阿里云文档
https://help.aliyun.com/document_detail/48871.html?spm=a2c4g.11186623.6.554.50d0735dC7GpQB  来源（Source）格式定义不一致, 

即调用方法 PostLogStoreLogsAsync 参数LogGroupInfo 属性 Source 设定默认值

**Comment by JasonMing** [comment]
fixed by #18
