### ISSUE TITLE
query date_format  error 401

### ISSUE THREAD

**Issue by liguobao** [aliyun/aliyun-log-dotnetcore-sdk#9]
query as 
```
* and kube-system  request: CreateUser and status:200 | select  date_format(__time__ -__time__%3600,'%Y-%m-%d')  as date ,count(*)  as count group by date order by date desc

```

error message:

{StatusCode: 401, ReasonPhrase: '', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:\r\n{\r\n

if remove date_format , the query is success.

**Comment by JasonMing** [comment]
401 indicates unauthorized, should not be related to SQL query.
@wind-tangkai please check this out.

**Comment by JasonMing** [comment]
no updates, close!
